### ISSUE TITLE
[member/create] Need 15 characters for "Social Security - Unique ID No"

### ISSUE THREAD

**Issue by dawansv** [dawansv/SS-Mali-Bugs#21]
People in Mali have a national id number but it is made of 14 digits and one letter, e.g. 12345678901234X -- so 15 characters total. Currently the field only accepts 12 characters.

Also related: currently when trying to save even only 12 characters, it only seems to save "0" in this field no matter what we put in it.

**Comment by Krishna-Manjari1204** [comment]
Resolved

**Comment by dawansv** [comment]
We are now able to enter 15 digits, however it does not save when putting number in [member/update]

**Comment by Krishna-Manjari1204** [comment]
Done

**Comment by dawansv** [comment]
@Krishna-Manjari1204 Unfortunately we are still getting an error message (picture of input screen first, then error message second)

<img width="2492" height="3752" alt="Image" src="https://github.com/user-attachments/assets/d97255d1-1d51-4450-ad93-55cd2a0799d1" />

<img width="2492" height="2338" alt="Image" src="https://github.com/user-attachments/assets/901f798b-b199-4277-bf23-13b8928c16fe" />

**Comment by Krishna-Manjari1204** [comment]
Resolved, Locally we consider only integer values in Unique ID No. Now it is updated to "varchar".

**Comment by dawansv** [comment]
Confirmed working. Thank you.
