### ISSUE TITLE
[clf/update&id=3] New village names appear blank in village drop-down list in French version only

### ISSUE THREAD

**Issue by dawansv** [dawansv/SS-Mali-Bugs#29]
We created 2 new villages and associated them to the Sadiola cluster. In the english version, then appear correctly in the list. In the French version, they do not. Although the codes are in the list, but the names are blank.

Screenshot of English version showing correct village names

![Image](https://github.com/user-attachments/assets/24ff9888-f861-4bc9-84c1-5d9c99ea63fe)

Screenshot of French version where names are blank

![Image](https://github.com/user-attachments/assets/ae2cef61-5e47-4593-8043-cf9fb0b46828)

**Comment by Krishna-Manjari1204** [comment]
At the time of village creation regional name of this villages submitted empty or database not inserted the French version names. We will check the case again. 
Please provide French names so that I can update.

<img width="237" height="443" alt="Image" src="https://github.com/user-attachments/assets/6731d23c-c52b-47b0-a751-2d210e85e040" />

**Comment by dawansv** [comment]
Interesting; not sure what happened that the regional_name wasn't saved. I think the other villages were entered from a bulk upload much earlier. These 2 new villages were entered "manually" via the interface. So possibly there is a problem with how the data is saved at that level.
For these 2 villages, regional_name is the same as name.

**Comment by Krishna-Manjari1204** [comment]
Resolved

**Comment by dawansv** [comment]
@Krishna-Manjari1204 We still have an error with updating VO profile. 
Now when trying to edit the VO Profile in the French Version, we get this error. We don't have the issue in the English version.

<img width="983" height="315" alt="Image" src="https://github.com/user-attachments/assets/b0fbd653-2ea0-444c-8194-3f3e83e396cf" />

<img width="2492" height="2767" alt="Image" src="https://github.com/user-attachments/assets/4244d145-787d-40e3-9e93-0f53c49bddd4" />

**Comment by dawansv** [comment]
We also get a similar error when trying to edit SHG Profile from this screen. Also only in French version.

<img width="1024" height="404" alt="Image" src="https://github.com/user-attachments/assets/596ca6d6-40b6-43f6-bd4f-dcbebe46d006" />

<img width="2492" height="2662" alt="Image" src="https://github.com/user-attachments/assets/d8eb8cde-29ec-49a9-9d09-56b3309ef11e" />

**Comment by Krishna-Manjari1204** [comment]
Resolved

**Comment by dawansv** [comment]
Confirmed working. Thank you!
